In [41]:
import numpy as np

In [42]:
lst = [1,2,3]
for n in lst:
    print(n*2, end=" ")
arr = np.array([1,2,3])
print(arr * 2)

2 4 6 [2 4 6]


In [43]:
# N-Dimentional Array in numpy
oned_arr = np.array([1,2,3,4,5])
print(oned_arr)

twod_arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(twod_arr)

threed_arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(threed_arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
#time taken by list VS numpy array
import time
start_time = time.time()
lst = [1,2,3,4,5,6,7,8,9]
sq = []
for n in lst:
    sq.append(n**2)
print("Time taken by List =", time.time() - start_time)

start_time = time.time()
arr = np.array([1,2,3,4,5,6,7,8,9])
sq = arr ** 2
print("Time taken by Numpy =", time.time() - start_time)

Time taken by List = 0.0
Time taken by Numpy = 0.0010061264038085938


In [31]:
# ndim - find the dimention of numpy array
print("First ", oned_arr.ndim)
print("Second ", twod_arr.ndim)
print("Third ", threed_arr.ndim)

First  1
Second  2
Third  3


In [45]:
# itemsize - you can calculate the size of each elements

newarr = np.array([1,2,3,4,5])
print(newarr.itemsize)

8


In [46]:
# dtype = find datatype of elements
arr1 = np.array([True, False, 1,2, 3.14])
print(arr1.dtype)

float64


In [48]:
print("First Size =", oned_arr.size)
print("First Shape =", oned_arr.shape)
print("Second Size =", twod_arr.size)
print("Second Shape =", twod_arr.shape)
print("Three Size =", threed_arr.size)
print("three Shape =", threed_arr.shape)

First Size = 5
First Shape = (5,)
Second Size = 6
Second Shape = (2, 3)
Three Size = 8
three Shape = (2, 2, 2)
