In [10]:
import numpy as np

In [5]:
oned_arr = np.array([1,2,3])
print(oned_arr)

[1 2 3]


In [9]:
twod_arr = np.array([
    [1,2],
    [3,4]
])
print(twod_arr)
print("Dimension =",twod_arr.ndim)

[[1 2]
 [3 4]]
Dimension = 2


# Reshape method
### Used to reshape numpy array

In [20]:
arr = np.array([
    [8,9,10],
    [11,12,13]
])

print("Shape of ARR =", arr.shape)

new_arr = arr.reshape(3,2)
print(new_arr)
print("Shape of New array", new_arr.shape)

Shape of ARR = (2, 3)
[[ 8  9]
 [10 11]
 [12 13]]
Shape of New array (3, 2)


## linspace
### 

In [27]:
arr_linear = np.linspace(1,5, 10, endpoint=True)
print(arr_linear)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## arange
### generate numbers between intervals

In [25]:
my_arr = np.arange(1,11, 2)
print(my_arr)

[1 3 5 7 9]


## Aggregate Funtions

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Minimum =", np.min(arr))
print("Maximum =",  np.max(arr))
print("Sum =",  np.sum(arr))
print("Average =",  np.mean(arr))

Minimum = 1
Maximum = 10
Sum = 55
Average = 5.5


In [37]:
arr = np.array([5,3,6,7,1,4,9,1])
print(np.sort(arr))

[1 1 3 4 5 6 7 9]


## Slicing

In [43]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

print("Sliced Part = ", arr[2:7])

arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Specific part =", arr_2d[1,0])
print("Sliced part of 2d =", arr_2d[:,1])

Sliced Part =  [30 40 50 60 70]
Specific part = 4
Sliced part of 2d = [2 5 8]
